<?php include( "contentsConAdm.php" );
   $id=mysqli_real_escape_string($con, $_POST['id']);
   $tujuan_prak=mysqli_real_escape_string($con, $_POST['tujuan_prak']);
   $sebutan_pimpinan=mysqli_real_escape_string($con, $_POST['sebutan_pimpinan']);
   $kota_prak=mysqli_real_escape_string($con, $_POST['kota_prak']);
   $jenjang_testee=mysqli_real_escape_string($con, $_POST['jenjang_testee']);
   $matkul=mysqli_real_escape_string($con, $_POST['matkul']);
   $waktu=mysqli_real_escape_string($con, $_POST['waktu']);
   $jam=mysqli_real_escape_string($con, $_POST['jam']);
   $tgl_pengajuan=mysqli_real_escape_string($con, $_POST['tgl_pengajuan']);
   $split = explode('-', $tgl_pengajuan);
   $bln_pengajuan= mysqli_real_escape_string($con, $split['1']);
   $thn_pengajuan= mysqli_real_escape_string($con, $split['2']);
   
   $testee1=mysqli_real_escape_string($con, $_POST['testee1']);
   $testee2=mysqli_real_escape_string($con, $_POST['testee2']);
   $testee3=mysqli_real_escape_string($con, $_POST['testee3']);
   $testee4=mysqli_real_escape_string($con, $_POST['testee4']);
   $testee5=mysqli_real_escape_string($con, $_POST['testee5']);
   $testee6=mysqli_real_escape_string($con, $_POST['testee6']);
   $testee7=mysqli_real_escape_string($con, $_POST['testee7']);
   $testee8=mysqli_real_escape_string($con, $_POST['testee8']);
   $testee9=mysqli_real_escape_string($con, $_POST['testee9']);
   $testee10=mysqli_real_escape_string($con, $_POST['testee10']);
   $testee11=mysqli_real_escape_string($con, $_POST['testee11']);
   $testee12=mysqli_real_escape_string($con, $_POST['testee12']);
   $testee13=mysqli_real_escape_string($con, $_POST['testee13']);
   $testee14=mysqli_real_escape_string($con, $_POST['testee14']);
   $testee15=mysqli_real_escape_string($con, $_POST['testee15']);
   $testee16=mysqli_real_escape_string($con, $_POST['testee16']);
   $testee17=mysqli_real_escape_string($con, $_POST['testee17']);
   $testee18=mysqli_real_escape_string($con, $_POST['testee18']);
   $testee19=mysqli_real_escape_string($con, $_POST['testee19']);
   $testee20=mysqli_real_escape_string($con, $_POST['testee20']);

   $myqry="UPDATE siprak_siswa SET tujuan_prak='$tujuan_prak',sebutan_pimpinan='$sebutan_pimpinan',kota_prak='$kota_prak',jenjang_testee='$jenjang_testee',matkul='$matkul',waktu='$waktu',jam='$jam',tgl_pengajuan='$tgl_pengajuan',bln_pengajuan='$bln_pengajuan',thn_pengajuan='$thn_pengajuan' WHERE id='$id' LIMIT 1";
       mysqli_query($con, $myqry) or die(mysqli_error($con));
       $qry="UPDATE testee_siprak SET nama_testee='$testee1' WHERE id_siprak='$id' AND urutan='1' LIMIT 1";
       mysqli_query($con, $qry) or die(mysqli_error($con));
       $qry="UPDATE testee_siprak SET nama_testee='$testee2' WHERE id_siprak='$id' AND urutan='2' LIMIT 1";
       mysqli_query($con, $qry) or die(mysqli_error($con));
       $qry="UPDATE testee_siprak SET nama_testee='$testee3' WHERE id_siprak='$id' AND urutan='3' LIMIT 1";
       mysqli_query($con, $qry) or die(mysqli_error($con));
       $qry="UPDATE testee_siprak SET nama_testee='$testee4' WHERE id_siprak='$id' AND urutan='4' LIMIT 1";
       mysqli_query($con, $qry) or die(mysqli_error($con));
       $qry="UPDATE testee_siprak SET nama_testee='$testee5' WHERE id_siprak='$id' AND urutan='5' LIMIT 1";
       mysqli_query($con, $qry) or die(mysqli_error($con));
       $qry="UPDATE testee_siprak SET nama_testee='$testee6' WHERE id_siprak='$id' AND urutan='6' LIMIT 1";
       mysqli_query($con, $qry) or die(mysqli_error($con));
       $qry="UPDATE testee_siprak SET nama_testee='$testee7' WHERE id_siprak='$id' AND urutan='7' LIMIT 1";
       mysqli_query($con, $qry) or die(mysqli_error($con));
       $qry="UPDATE testee_siprak SET nama_testee='$testee8' WHERE id_siprak='$id' AND urutan='8' LIMIT 1";
       mysqli_query($con, $qry) or die(mysqli_error($con));
       $qry="UPDATE testee_siprak SET nama_testee='$testee9' WHERE id_siprak='$id' AND urutan='9' LIMIT 1";
       mysqli_query($con, $qry) or die(mysqli_error($con));
       $qry="UPDATE testee_siprak SET nama_testee='$testee10' WHERE id_siprak='$id' AND urutan='10' LIMIT 1";
       mysqli_query($con, $qry) or die(mysqli_error($con));
       $qry="UPDATE testee_siprak SET nama_testee='$testee11' WHERE id_siprak='$id' AND urutan='11' LIMIT 1";
       mysqli_query($con, $qry) or die(mysqli_error($con));
       $qry="UPDATE testee_siprak SET nama_testee='$testee12' WHERE id_siprak='$id' AND urutan='12' LIMIT 1";
       mysqli_query($con, $qry) or die(mysqli_error($con));
       $qry="UPDATE testee_siprak SET nama_testee='$testee13' WHERE id_siprak='$id' AND urutan='13' LIMIT 1";
       mysqli_query($con, $qry) or die(mysqli_error($con));
       $qry="UPDATE testee_siprak SET nama_testee='$testee14' WHERE id_siprak='$id' AND urutan='14' LIMIT 1";
       mysqli_query($con, $qry) or die(mysqli_error($con));
       $qry="UPDATE testee_siprak SET nama_testee='$testee15' WHERE id_siprak='$id' AND urutan='15' LIMIT 1";
       mysqli_query($con, $qry) or die(mysqli_error($con));
       $qry="UPDATE testee_siprak SET nama_testee='$testee16' WHERE id_siprak='$id' AND urutan='16' LIMIT 1";
       mysqli_query($con, $qry) or die(mysqli_error($con));
       $qry="UPDATE testee_siprak SET nama_testee='$testee17' WHERE id_siprak='$id' AND urutan='17' LIMIT 1";
       mysqli_query($con, $qry) or die(mysqli_error($con));
       $qry="UPDATE testee_siprak SET nama_testee='$testee18' WHERE id_siprak='$id' AND urutan='18' LIMIT 1";
       mysqli_query($con, $qry) or die(mysqli_error($con));
       $qry="UPDATE testee_siprak SET nama_testee='$testee19' WHERE id_siprak='$id' AND urutan='19' LIMIT 1";
       mysqli_query($con, $qry) or die(mysqli_error($con));
       $qry="UPDATE testee_siprak SET nama_testee='$testee20' WHERE id_siprak='$id' AND urutan='20' LIMIT 1";
       mysqli_query($con, $qry) or die(mysqli_error($con));

       header("location:riwayatSiprakksUser.php?message=notifEdit");
   ?>