<?php include( "contentsConAdm.php" );

   $id=mysqli_real_escape_string($con, $_POST['id']);
   $page= mysqli_real_escape_string($con, $_POST['page']);
   $date= mysqli_real_escape_string($con, $_POST['date']);
   $no_agenda_surat=mysqli_real_escape_string($con, $_POST['no_agenda_surat']);
   $matkul_testee=mysqli_real_escape_string($con, $_POST['matkul_testee']);
   $dosen_testee=mysqli_real_escape_string($con, $_POST['dosen_testee']);
   $matkul=mysqli_real_escape_string($con, $_POST['matkul']);
   $waktu=mysqli_real_escape_string($con, $_POST['waktu']);
   $jam=mysqli_real_escape_string($con, $_POST['jam']);
   $tgl_dikeluarkan=mysqli_real_escape_string($con, $_POST['tgl_dikeluarkan']);
   $tgl_proses=date('d-m-Y');
   $tembusan=mysqli_real_escape_string($con, $_POST['tembusan']);
   $statusform=mysqli_real_escape_string($con, '2');
   $executor=mysqli_real_escape_string($con, $_POST['executor']);   
   
   $testee1=mysqli_real_escape_string($con, $_POST['testee1']);	$nim_testee1=mysqli_real_escape_string($con, $_POST['nim_testee1']);
   $testee2=mysqli_real_escape_string($con, $_POST['testee2']);	$nim_testee2=mysqli_real_escape_string($con, $_POST['nim_testee2']);
   $testee3=mysqli_real_escape_string($con, $_POST['testee3']);	$nim_testee3=mysqli_real_escape_string($con, $_POST['nim_testee3']);
   $testee4=mysqli_real_escape_string($con, $_POST['testee4']);	$nim_testee4=mysqli_real_escape_string($con, $_POST['nim_testee4']);
   $testee5=mysqli_real_escape_string($con, $_POST['testee5']);	$nim_testee5=mysqli_real_escape_string($con, $_POST['nim_testee5']);
   $testee6=mysqli_real_escape_string($con, $_POST['testee6']);	$nim_testee6=mysqli_real_escape_string($con, $_POST['nim_testee6']);
   $testee7=mysqli_real_escape_string($con, $_POST['testee7']);	$nim_testee7=mysqli_real_escape_string($con, $_POST['nim_testee7']);
   $testee8=mysqli_real_escape_string($con, $_POST['testee8']);	$nim_testee8=mysqli_real_escape_string($con, $_POST['nim_testee8']);
   $testee9=mysqli_real_escape_string($con, $_POST['testee9']);	$nim_testee9=mysqli_real_escape_string($con, $_POST['nim_testee9']);
   $testee10=mysqli_real_escape_string($con, $_POST['testee10']);	$nim_testee10=mysqli_real_escape_string($con, $_POST['nim_testee10']);
   $testee11=mysqli_real_escape_string($con, $_POST['testee11']);	$nim_testee11=mysqli_real_escape_string($con, $_POST['nim_testee11']);
   $testee12=mysqli_real_escape_string($con, $_POST['testee12']);	$nim_testee12=mysqli_real_escape_string($con, $_POST['nim_testee12']);
   $testee13=mysqli_real_escape_string($con, $_POST['testee13']);	$nim_testee13=mysqli_real_escape_string($con, $_POST['nim_testee13']);
   $testee14=mysqli_real_escape_string($con, $_POST['testee14']);	$nim_testee14=mysqli_real_escape_string($con, $_POST['nim_testee14']);
   $testee15=mysqli_real_escape_string($con, $_POST['testee15']);	$nim_testee15=mysqli_real_escape_string($con, $_POST['nim_testee15']);
   $testee16=mysqli_real_escape_string($con, $_POST['testee16']);	$nim_testee16=mysqli_real_escape_string($con, $_POST['nim_testee16']);
   $testee17=mysqli_real_escape_string($con, $_POST['testee17']);	$nim_testee17=mysqli_real_escape_string($con, $_POST['nim_testee17']);
   $testee18=mysqli_real_escape_string($con, $_POST['testee18']);	$nim_testee18=mysqli_real_escape_string($con, $_POST['nim_testee18']);
   $testee19=mysqli_real_escape_string($con, $_POST['testee19']);	$nim_testee19=mysqli_real_escape_string($con, $_POST['nim_testee19']);
   $testee20=mysqli_real_escape_string($con, $_POST['testee20']);	$nim_testee20=mysqli_real_escape_string($con, $_POST['nim_testee20']);

   $myqry="UPDATE siprak_mahasiswa SET no_agenda_surat='$no_agenda_surat',matkul_testee='$matkul_testee',dosen_testee='$dosen_testee',matkul='$matkul',waktu='$waktu',jam='$jam',tgl_proses='$tgl_proses',tgl_dikeluarkan='$tgl_dikeluarkan',tembusan='$tembusan',statusform='$statusform',executor='$executor' WHERE id='$id' LIMIT 1";
   mysqli_query($con, $myqry) or die(mysqli_error($con));
	$qry="UPDATE testee_siprak SET nama_testee='$testee1',nim='$nim_testee1' WHERE id_siprak='$id' AND urutan='1' LIMIT 1";
   mysqli_query($con, $qry) or die(mysqli_error($con));
   $qry="UPDATE testee_siprak SET nama_testee='$testee2',nim='$nim_testee2' WHERE id_siprak='$id' AND urutan='2' LIMIT 1";
   mysqli_query($con, $qry) or die(mysqli_error($con));
	$qry="UPDATE testee_siprak SET nama_testee='$testee3',nim='$nim_testee3' WHERE id_siprak='$id' AND urutan='3' LIMIT 1";
   mysqli_query($con, $qry) or die(mysqli_error($con));
	$qry="UPDATE testee_siprak SET nama_testee='$testee4',nim='$nim_testee4' WHERE id_siprak='$id' AND urutan='4' LIMIT 1";
   mysqli_query($con, $qry) or die(mysqli_error($con));
	$qry="UPDATE testee_siprak SET nama_testee='$testee5',nim='$nim_testee5' WHERE id_siprak='$id' AND urutan='5' LIMIT 1";
   mysqli_query($con, $qry) or die(mysqli_error($con));
	$qry="UPDATE testee_siprak SET nama_testee='$testee6',nim='$nim_testee6' WHERE id_siprak='$id' AND urutan='6' LIMIT 1";
   mysqli_query($con, $qry) or die(mysqli_error($con));
	$qry="UPDATE testee_siprak SET nama_testee='$testee7',nim='$nim_testee7' WHERE id_siprak='$id' AND urutan='7' LIMIT 1";
   mysqli_query($con, $qry) or die(mysqli_error($con));
	$qry="UPDATE testee_siprak SET nama_testee='$testee8',nim='$nim_testee8' WHERE id_siprak='$id' AND urutan='8' LIMIT 1";
   mysqli_query($con, $qry) or die(mysqli_error($con));
	$qry="UPDATE testee_siprak SET nama_testee='$testee9',nim='$nim_testee9' WHERE id_siprak='$id' AND urutan='9' LIMIT 1";
   mysqli_query($con, $qry) or die(mysqli_error($con));
	$qry="UPDATE testee_siprak SET nama_testee='$testee10',nim='$nim_testee10' WHERE id_siprak='$id' AND urutan='10' LIMIT 1";
   mysqli_query($con, $qry) or die(mysqli_error($con));
	$qry="UPDATE testee_siprak SET nama_testee='$testee11',nim='$nim_testee11' WHERE id_siprak='$id' AND urutan='11' LIMIT 1";
   mysqli_query($con, $qry) or die(mysqli_error($con));
	$qry="UPDATE testee_siprak SET nama_testee='$testee12',nim='$nim_testee12' WHERE id_siprak='$id' AND urutan='12' LIMIT 1";
   mysqli_query($con, $qry) or die(mysqli_error($con));
	$qry="UPDATE testee_siprak SET nama_testee='$testee13',nim='$nim_testee13' WHERE id_siprak='$id' AND urutan='13' LIMIT 1";
   mysqli_query($con, $qry) or die(mysqli_error($con));
	$qry="UPDATE testee_siprak SET nama_testee='$testee14',nim='$nim_testee14' WHERE id_siprak='$id' AND urutan='14' LIMIT 1";
   mysqli_query($con, $qry) or die(mysqli_error($con));
	$qry="UPDATE testee_siprak SET nama_testee='$testee15',nim='$nim_testee15' WHERE id_siprak='$id' AND urutan='15' LIMIT 1";
   mysqli_query($con, $qry) or die(mysqli_error($con));
	$qry="UPDATE testee_siprak SET nama_testee='$testee16',nim='$nim_testee16' WHERE id_siprak='$id' AND urutan='16' LIMIT 1";
   mysqli_query($con, $qry) or die(mysqli_error($con));
	$qry="UPDATE testee_siprak SET nama_testee='$testee17',nim='$nim_testee17' WHERE id_siprak='$id' AND urutan='17' LIMIT 1";
   mysqli_query($con, $qry) or die(mysqli_error($con));
	$qry="UPDATE testee_siprak SET nama_testee='$testee18',nim='$nim_testee18' WHERE id_siprak='$id' AND urutan='18' LIMIT 1";
   mysqli_query($con, $qry) or die(mysqli_error($con));
	$qry="UPDATE testee_siprak SET nama_testee='$testee19',nim='$nim_testee19' WHERE id_siprak='$id' AND urutan='19' LIMIT 1";
   mysqli_query($con, $qry) or die(mysqli_error($con));
	$qry="UPDATE testee_siprak SET nama_testee='$testee20',nim='$nim_testee20' WHERE id_siprak='$id' AND urutan='20' LIMIT 1";
   mysqli_query($con, $qry) or die(mysqli_error($con));

   header("location:rekapSiprakMhsswKelAdm.php?date=$date&page=$page&message=notifEdit");
   ?>