<?php include( "contentsConAdm.php" );
   $id=mysqli_real_escape_string($con, $_POST['id']);
   $page_a=mysqli_real_escape_string($con, $_POST['page_a']);
   $tahun=mysqli_real_escape_string($con, $_POST['tahun']);
   $page=mysqli_real_escape_string($con, $_POST['page']);
   $no_agenda_surat=mysqli_real_escape_string($con, $_POST['no_agenda_surat']);
   $perihal=mysqli_real_escape_string($con, $_POST['perihal']);
   $dasar=mysqli_real_escape_string($con, $_POST['dasar']);
   $awal_berlaku=mysqli_real_escape_string($con, $_POST['awal_berlaku']);   
   $akhir_berlaku=mysqli_real_escape_string($con, $_POST['akhir_berlaku']);
   $tgl_ditetapkan=mysqli_real_escape_string($con, $_POST['tgl_ditetapkan']);
   $editor=mysqli_real_escape_string($con, $_POST['editor']);
   
   $nama1=mysqli_real_escape_string($con, $_POST['nama1']);
   $nama2=mysqli_real_escape_string($con, $_POST['nama2']);
   $nama3=mysqli_real_escape_string($con, $_POST['nama3']);
   $nama4=mysqli_real_escape_string($con, $_POST['nama4']);
   $nama5=mysqli_real_escape_string($con, $_POST['nama5']);
   $nama6=mysqli_real_escape_string($con, $_POST['nama6']);
   $nama7=mysqli_real_escape_string($con, $_POST['nama7']);
   $nama8=mysqli_real_escape_string($con, $_POST['nama8']);
   $nama9=mysqli_real_escape_string($con, $_POST['nama9']);
   $nama10=mysqli_real_escape_string($con, $_POST['nama10']);
   $nama11=mysqli_real_escape_string($con, $_POST['nama11']);
   $nama12=mysqli_real_escape_string($con, $_POST['nama12']);
   $nama13=mysqli_real_escape_string($con, $_POST['nama13']);
   $nama14=mysqli_real_escape_string($con, $_POST['nama14']);
   $nama15=mysqli_real_escape_string($con, $_POST['nama15']);
   $nama16=mysqli_real_escape_string($con, $_POST['nama16']);
   $nama17=mysqli_real_escape_string($con, $_POST['nama17']);
   $nama18=mysqli_real_escape_string($con, $_POST['nama18']);
   $nama19=mysqli_real_escape_string($con, $_POST['nama19']);
   $nama20=mysqli_real_escape_string($con, $_POST['nama20']);
   $nama21=mysqli_real_escape_string($con, $_POST['nama21']);
   $nama22=mysqli_real_escape_string($con, $_POST['nama22']);
   $nama23=mysqli_real_escape_string($con, $_POST['nama23']);
   $nama24=mysqli_real_escape_string($con, $_POST['nama24']);
   $nama25=mysqli_real_escape_string($con, $_POST['nama25']);
   $nama26=mysqli_real_escape_string($con, $_POST['nama26']);
   $nama27=mysqli_real_escape_string($con, $_POST['nama27']);
   $nama28=mysqli_real_escape_string($con, $_POST['nama28']);
   $nama29=mysqli_real_escape_string($con, $_POST['nama29']);
   $nama30=mysqli_real_escape_string($con, $_POST['nama30']);
   $nama31=mysqli_real_escape_string($con, $_POST['nama31']);
   $nama32=mysqli_real_escape_string($con, $_POST['nama32']);
   $nama33=mysqli_real_escape_string($con, $_POST['nama33']);
   $nama34=mysqli_real_escape_string($con, $_POST['nama34']);
   $nama35=mysqli_real_escape_string($con, $_POST['nama35']);
   $nama36=mysqli_real_escape_string($con, $_POST['nama36']);
   $nama37=mysqli_real_escape_string($con, $_POST['nama37']);
   $nama38=mysqli_real_escape_string($con, $_POST['nama38']);
   $nama39=mysqli_real_escape_string($con, $_POST['nama39']);
   $nama40=mysqli_real_escape_string($con, $_POST['nama40']);
   $nama41=mysqli_real_escape_string($con, $_POST['nama41']);
   $nama42=mysqli_real_escape_string($con, $_POST['nama42']);
   $nama43=mysqli_real_escape_string($con, $_POST['nama43']);
   $nama44=mysqli_real_escape_string($con, $_POST['nama44']);
   $nama45=mysqli_real_escape_string($con, $_POST['nama45']);
   $nama46=mysqli_real_escape_string($con, $_POST['nama46']);
   $nama47=mysqli_real_escape_string($con, $_POST['nama47']);
   $nama48=mysqli_real_escape_string($con, $_POST['nama48']);
   $nama49=mysqli_real_escape_string($con, $_POST['nama49']);
   $nama50=mysqli_real_escape_string($con, $_POST['nama50']);
   $nama51=mysqli_real_escape_string($con, $_POST['nama51']);
   $nama52=mysqli_real_escape_string($con, $_POST['nama52']);
   $nama53=mysqli_real_escape_string($con, $_POST['nama53']);
   $nama54=mysqli_real_escape_string($con, $_POST['nama54']);
   $nama55=mysqli_real_escape_string($con, $_POST['nama55']);
   $nama56=mysqli_real_escape_string($con, $_POST['nama56']);
   $nama57=mysqli_real_escape_string($con, $_POST['nama57']);
   $nama58=mysqli_real_escape_string($con, $_POST['nama58']);
   $nama59=mysqli_real_escape_string($con, $_POST['nama59']);
   $nama60=mysqli_real_escape_string($con, $_POST['nama60']);
   $nama61=mysqli_real_escape_string($con, $_POST['nama61']);
   $nama62=mysqli_real_escape_string($con, $_POST['nama62']);
   $nama63=mysqli_real_escape_string($con, $_POST['nama63']);
   $nama64=mysqli_real_escape_string($con, $_POST['nama64']);
   $nama65=mysqli_real_escape_string($con, $_POST['nama65']);
   
   $jabatan1=mysqli_real_escape_string($con, $_POST['jabatan1']);
   $jabatan2=mysqli_real_escape_string($con, $_POST['jabatan2']);
   $jabatan3=mysqli_real_escape_string($con, $_POST['jabatan3']);
   $jabatan4=mysqli_real_escape_string($con, $_POST['jabatan4']);
   $jabatan5=mysqli_real_escape_string($con, $_POST['jabatan5']);
   $jabatan6=mysqli_real_escape_string($con, $_POST['jabatan6']);
   $jabatan7=mysqli_real_escape_string($con, $_POST['jabatan7']);
   $jabatan8=mysqli_real_escape_string($con, $_POST['jabatan8']);
   $jabatan9=mysqli_real_escape_string($con, $_POST['jabatan9']);
   $jabatan10=mysqli_real_escape_string($con, $_POST['jabatan10']);
   $jabatan11=mysqli_real_escape_string($con, $_POST['jabatan11']);
   $jabatan12=mysqli_real_escape_string($con, $_POST['jabatan12']);
   $jabatan13=mysqli_real_escape_string($con, $_POST['jabatan13']);
   $jabatan14=mysqli_real_escape_string($con, $_POST['jabatan14']);
   $jabatan15=mysqli_real_escape_string($con, $_POST['jabatan15']);
   $jabatan16=mysqli_real_escape_string($con, $_POST['jabatan16']);
   $jabatan17=mysqli_real_escape_string($con, $_POST['jabatan17']);
   $jabatan18=mysqli_real_escape_string($con, $_POST['jabatan18']);
   $jabatan19=mysqli_real_escape_string($con, $_POST['jabatan19']);
   $jabatan20=mysqli_real_escape_string($con, $_POST['jabatan20']);
   $jabatan21=mysqli_real_escape_string($con, $_POST['jabatan21']);
   $jabatan22=mysqli_real_escape_string($con, $_POST['jabatan22']);
   $jabatan23=mysqli_real_escape_string($con, $_POST['jabatan23']);
   $jabatan24=mysqli_real_escape_string($con, $_POST['jabatan24']);
   $jabatan25=mysqli_real_escape_string($con, $_POST['jabatan25']);
   $jabatan26=mysqli_real_escape_string($con, $_POST['jabatan26']);
   $jabatan27=mysqli_real_escape_string($con, $_POST['jabatan27']);
   $jabatan28=mysqli_real_escape_string($con, $_POST['jabatan28']);
   $jabatan29=mysqli_real_escape_string($con, $_POST['jabatan29']);
   $jabatan30=mysqli_real_escape_string($con, $_POST['jabatan30']);
   $jabatan31=mysqli_real_escape_string($con, $_POST['jabatan31']);
   $jabatan32=mysqli_real_escape_string($con, $_POST['jabatan32']);
   $jabatan33=mysqli_real_escape_string($con, $_POST['jabatan33']);
   $jabatan34=mysqli_real_escape_string($con, $_POST['jabatan34']);
   $jabatan35=mysqli_real_escape_string($con, $_POST['jabatan35']);
   $jabatan36=mysqli_real_escape_string($con, $_POST['jabatan36']);
   $jabatan37=mysqli_real_escape_string($con, $_POST['jabatan37']);
   $jabatan38=mysqli_real_escape_string($con, $_POST['jabatan38']);
   $jabatan39=mysqli_real_escape_string($con, $_POST['jabatan39']);
   $jabatan40=mysqli_real_escape_string($con, $_POST['jabatan40']);
   $jabatan41=mysqli_real_escape_string($con, $_POST['jabatan41']);
   $jabatan42=mysqli_real_escape_string($con, $_POST['jabatan42']);
   $jabatan43=mysqli_real_escape_string($con, $_POST['jabatan43']);
   $jabatan44=mysqli_real_escape_string($con, $_POST['jabatan44']);
   $jabatan45=mysqli_real_escape_string($con, $_POST['jabatan45']);
   $jabatan46=mysqli_real_escape_string($con, $_POST['jabatan46']);
   $jabatan47=mysqli_real_escape_string($con, $_POST['jabatan47']);
   $jabatan48=mysqli_real_escape_string($con, $_POST['jabatan48']);
   $jabatan49=mysqli_real_escape_string($con, $_POST['jabatan49']);
   $jabatan50=mysqli_real_escape_string($con, $_POST['jabatan50']);
   $jabatan51=mysqli_real_escape_string($con, $_POST['jabatan51']);
   $jabatan52=mysqli_real_escape_string($con, $_POST['jabatan52']);
   $jabatan53=mysqli_real_escape_string($con, $_POST['jabatan53']);
   $jabatan54=mysqli_real_escape_string($con, $_POST['jabatan54']);
   $jabatan55=mysqli_real_escape_string($con, $_POST['jabatan55']);
   $jabatan56=mysqli_real_escape_string($con, $_POST['jabatan56']);
   $jabatan57=mysqli_real_escape_string($con, $_POST['jabatan57']);
   $jabatan58=mysqli_real_escape_string($con, $_POST['jabatan58']);
   $jabatan59=mysqli_real_escape_string($con, $_POST['jabatan59']);
   $jabatan60=mysqli_real_escape_string($con, $_POST['jabatan60']);
   $jabatan61=mysqli_real_escape_string($con, $_POST['jabatan61']);
   $jabatan62=mysqli_real_escape_string($con, $_POST['jabatan62']);
   $jabatan63=mysqli_real_escape_string($con, $_POST['jabatan63']);
   $jabatan64=mysqli_real_escape_string($con, $_POST['jabatan64']);
   $jabatan65=mysqli_real_escape_string($con, $_POST['jabatan65']);
   
   //* st * //
   $myqry="UPDATE st SET no_agenda_surat='$no_agenda_surat',perihal='$perihal',dasar='$dasar',awal_berlaku='$awal_berlaku',akhir_berlaku='$akhir_berlaku',tgl_ditetapkan='$tgl_ditetapkan',editor='$editor' WHERE id='$id' LIMIT 1";
   mysqli_query($con, $myqry) or die(mysqli_error($con));
   
   //* personil * //
   $qry="UPDATE personil_st SET nama='$nama1',jabatan_st='$jabatan1' WHERE id_st='$id' AND urutan='1' LIMIT 1";
   mysqli_query($con, $qry) or die(mysqli_error($con));
   $qry="UPDATE personil_st SET nama='$nama2',jabatan_st='$jabatan2' WHERE id_st='$id' AND urutan='2' LIMIT 1";
   mysqli_query($con, $qry) or die(mysqli_error($con));
   $qry="UPDATE personil_st SET nama='$nama3',jabatan_st='$jabatan3' WHERE id_st='$id' AND urutan='3' LIMIT 1";
   mysqli_query($con, $qry) or die(mysqli_error($con));
   $qry="UPDATE personil_st SET nama='$nama4',jabatan_st='$jabatan4' WHERE id_st='$id' AND urutan='4' LIMIT 1";
   mysqli_query($con, $qry) or die(mysqli_error($con));
   $qry="UPDATE personil_st SET nama='$nama5',jabatan_st='$jabatan5' WHERE id_st='$id' AND urutan='5' LIMIT 1";
   mysqli_query($con, $qry) or die(mysqli_error($con));
   $qry="UPDATE personil_st SET nama='$nama6',jabatan_st='$jabatan6' WHERE id_st='$id' AND urutan='6' LIMIT 1";
   mysqli_query($con, $qry) or die(mysqli_error($con));
   $qry="UPDATE personil_st SET nama='$nama7',jabatan_st='$jabatan7' WHERE id_st='$id' AND urutan='7' LIMIT 1";
   mysqli_query($con, $qry) or die(mysqli_error($con));
   $qry="UPDATE personil_st SET nama='$nama8',jabatan_st='$jabatan8' WHERE id_st='$id' AND urutan='8' LIMIT 1";
   mysqli_query($con, $qry) or die(mysqli_error($con));
   $qry="UPDATE personil_st SET nama='$nama9',jabatan_st='$jabatan9' WHERE id_st='$id' AND urutan='9' LIMIT 1";
   mysqli_query($con, $qry) or die(mysqli_error($con));
   $qry="UPDATE personil_st SET nama='$nama10',jabatan_st='$jabatan10' WHERE id_st='$id' AND urutan='10' LIMIT 1";
   mysqli_query($con, $qry) or die(mysqli_error($con));
   $qry="UPDATE personil_st SET nama='$nama11',jabatan_st='$jabatan11' WHERE id_st='$id' AND urutan='11' LIMIT 1";
   mysqli_query($con, $qry) or die(mysqli_error($con));
   $qry="UPDATE personil_st SET nama='$nama12',jabatan_st='$jabatan12' WHERE id_st='$id' AND urutan='12' LIMIT 1";
   mysqli_query($con, $qry) or die(mysqli_error($con));
   $qry="UPDATE personil_st SET nama='$nama13',jabatan_st='$jabatan13' WHERE id_st='$id' AND urutan='13' LIMIT 1";
   mysqli_query($con, $qry) or die(mysqli_error($con));
   $qry="UPDATE personil_st SET nama='$nama14',jabatan_st='$jabatan14' WHERE id_st='$id' AND urutan='14' LIMIT 1";
   mysqli_query($con, $qry) or die(mysqli_error($con));
   $qry="UPDATE personil_st SET nama='$nama14',jabatan_st='$jabatan14' WHERE id_st='$id' AND urutan='14' LIMIT 1";
   mysqli_query($con, $qry) or die(mysqli_error($con));
   $qry="UPDATE personil_st SET nama='$nama15',jabatan_st='$jabatan15' WHERE id_st='$id' AND urutan='15' LIMIT 1";
   mysqli_query($con, $qry) or die(mysqli_error($con));
   $qry="UPDATE personil_st SET nama='$nama16',jabatan_st='$jabatan16' WHERE id_st='$id' AND urutan='16' LIMIT 1";
   mysqli_query($con, $qry) or die(mysqli_error($con));
   $qry="UPDATE personil_st SET nama='$nama17',jabatan_st='$jabatan17' WHERE id_st='$id' AND urutan='17' LIMIT 1";
   mysqli_query($con, $qry) or die(mysqli_error($con));
   $qry="UPDATE personil_st SET nama='$nama18',jabatan_st='$jabatan18' WHERE id_st='$id' AND urutan='18' LIMIT 1";
   mysqli_query($con, $qry) or die(mysqli_error($con));
   $qry="UPDATE personil_st SET nama='$nama19',jabatan_st='$jabatan19' WHERE id_st='$id' AND urutan='19' LIMIT 1";
   mysqli_query($con, $qry) or die(mysqli_error($con));
   $qry="UPDATE personil_st SET nama='$nama20',jabatan_st='$jabatan20' WHERE id_st='$id' AND urutan='20' LIMIT 1";
   mysqli_query($con, $qry) or die(mysqli_error($con));
   $qry="UPDATE personil_st SET nama='$nama21',jabatan_st='$jabatan21' WHERE id_st='$id' AND urutan='21' LIMIT 1";
   mysqli_query($con, $qry) or die(mysqli_error($con));
   $qry="UPDATE personil_st SET nama='$nama22',jabatan_st='$jabatan22' WHERE id_st='$id' AND urutan='22' LIMIT 1";
   mysqli_query($con, $qry) or die(mysqli_error($con));
   $qry="UPDATE personil_st SET nama='$nama23',jabatan_st='$jabatan23' WHERE id_st='$id' AND urutan='23' LIMIT 1";
   mysqli_query($con, $qry) or die(mysqli_error($con));
   $qry="UPDATE personil_st SET nama='$nama24',jabatan_st='$jabatan24' WHERE id_st='$id' AND urutan='24' LIMIT 1";
   mysqli_query($con, $qry) or die(mysqli_error($con));
   $qry="UPDATE personil_st SET nama='$nama25',jabatan_st='$jabatan25' WHERE id_st='$id' AND urutan='25' LIMIT 1";
   mysqli_query($con, $qry) or die(mysqli_error($con));
   $qry="UPDATE personil_st SET nama='$nama26',jabatan_st='$jabatan26' WHERE id_st='$id' AND urutan='26' LIMIT 1";
   mysqli_query($con, $qry) or die(mysqli_error($con));
   $qry="UPDATE personil_st SET nama='$nama27',jabatan_st='$jabatan27' WHERE id_st='$id' AND urutan='27' LIMIT 1";
   mysqli_query($con, $qry) or die(mysqli_error($con));
   $qry="UPDATE personil_st SET nama='$nama28',jabatan_st='$jabatan28' WHERE id_st='$id' AND urutan='28' LIMIT 1";
   mysqli_query($con, $qry) or die(mysqli_error($con));
   $qry="UPDATE personil_st SET nama='$nama29',jabatan_st='$jabatan29' WHERE id_st='$id' AND urutan='29' LIMIT 1";
   mysqli_query($con, $qry) or die(mysqli_error($con));
   $qry="UPDATE personil_st SET nama='$nama30',jabatan_st='$jabatan30' WHERE id_st='$id' AND urutan='30' LIMIT 1";
   mysqli_query($con, $qry) or die(mysqli_error($con));
   $qry="UPDATE personil_st SET nama='$nama31',jabatan_st='$jabatan31' WHERE id_st='$id' AND urutan='31' LIMIT 1";
   mysqli_query($con, $qry) or die(mysqli_error($con));
   $qry="UPDATE personil_st SET nama='$nama32',jabatan_st='$jabatan32' WHERE id_st='$id' AND urutan='32' LIMIT 1";
   mysqli_query($con, $qry) or die(mysqli_error($con));
   $qry="UPDATE personil_st SET nama='$nama33',jabatan_st='$jabatan33' WHERE id_st='$id' AND urutan='33' LIMIT 1";
   mysqli_query($con, $qry) or die(mysqli_error($con));
   $qry="UPDATE personil_st SET nama='$nama34',jabatan_st='$jabatan34' WHERE id_st='$id' AND urutan='34' LIMIT 1";
   mysqli_query($con, $qry) or die(mysqli_error($con));
   $qry="UPDATE personil_st SET nama='$nama35',jabatan_st='$jabatan35' WHERE id_st='$id' AND urutan='35' LIMIT 1";
   mysqli_query($con, $qry) or die(mysqli_error($con));
   $qry="UPDATE personil_st SET nama='$nama36',jabatan_st='$jabatan36' WHERE id_st='$id' AND urutan='36' LIMIT 1";
   mysqli_query($con, $qry) or die(mysqli_error($con));
   $qry="UPDATE personil_st SET nama='$nama37',jabatan_st='$jabatan37' WHERE id_st='$id' AND urutan='37' LIMIT 1";
   mysqli_query($con, $qry) or die(mysqli_error($con));
   $qry="UPDATE personil_st SET nama='$nama38',jabatan_st='$jabatan38' WHERE id_st='$id' AND urutan='38' LIMIT 1";
   mysqli_query($con, $qry) or die(mysqli_error($con));
   $qry="UPDATE personil_st SET nama='$nama39',jabatan_st='$jabatan39' WHERE id_st='$id' AND urutan='39' LIMIT 1";
   mysqli_query($con, $qry) or die(mysqli_error($con));
   $qry="UPDATE personil_st SET nama='$nama40',jabatan_st='$jabatan40' WHERE id_st='$id' AND urutan='40' LIMIT 1";
   mysqli_query($con, $qry) or die(mysqli_error($con));
   $qry="UPDATE personil_st SET nama='$nama41',jabatan_st='$jabatan41' WHERE id_st='$id' AND urutan='41' LIMIT 1";
   mysqli_query($con, $qry) or die(mysqli_error($con));
   $qry="UPDATE personil_st SET nama='$nama42',jabatan_st='$jabatan42' WHERE id_st='$id' AND urutan='42' LIMIT 1";
   mysqli_query($con, $qry) or die(mysqli_error($con));
   $qry="UPDATE personil_st SET nama='$nama43',jabatan_st='$jabatan43' WHERE id_st='$id' AND urutan='43' LIMIT 1";
   mysqli_query($con, $qry) or die(mysqli_error($con));
   $qry="UPDATE personil_st SET nama='$nama44',jabatan_st='$jabatan44' WHERE id_st='$id' AND urutan='44' LIMIT 1";
   mysqli_query($con, $qry) or die(mysqli_error($con));
   $qry="UPDATE personil_st SET nama='$nama45',jabatan_st='$jabatan45' WHERE id_st='$id' AND urutan='45' LIMIT 1";
   mysqli_query($con, $qry) or die(mysqli_error($con));
   $qry="UPDATE personil_st SET nama='$nama46',jabatan_st='$jabatan46' WHERE id_st='$id' AND urutan='46' LIMIT 1";
   mysqli_query($con, $qry) or die(mysqli_error($con));
   $qry="UPDATE personil_st SET nama='$nama47',jabatan_st='$jabatan47' WHERE id_st='$id' AND urutan='47' LIMIT 1";
   mysqli_query($con, $qry) or die(mysqli_error($con));
   $qry="UPDATE personil_st SET nama='$nama48',jabatan_st='$jabatan48' WHERE id_st='$id' AND urutan='48' LIMIT 1";
   mysqli_query($con, $qry) or die(mysqli_error($con));
   $qry="UPDATE personil_st SET nama='$nama49',jabatan_st='$jabatan49' WHERE id_st='$id' AND urutan='49' LIMIT 1";
   mysqli_query($con, $qry) or die(mysqli_error($con));
   $qry="UPDATE personil_st SET nama='$nama50',jabatan_st='$jabatan50' WHERE id_st='$id' AND urutan='50' LIMIT 1";
   mysqli_query($con, $qry) or die(mysqli_error($con));
   $qry="UPDATE personil_st SET nama='$nama51',jabatan_st='$jabatan51' WHERE id_st='$id' AND urutan='51' LIMIT 1";
   mysqli_query($con, $qry) or die(mysqli_error($con));
   $qry="UPDATE personil_st SET nama='$nama52',jabatan_st='$jabatan52' WHERE id_st='$id' AND urutan='52' LIMIT 1";
   mysqli_query($con, $qry) or die(mysqli_error($con));
   $qry="UPDATE personil_st SET nama='$nama53',jabatan_st='$jabatan53' WHERE id_st='$id' AND urutan='53' LIMIT 1";
   mysqli_query($con, $qry) or die(mysqli_error($con));
   $qry="UPDATE personil_st SET nama='$nama54',jabatan_st='$jabatan54' WHERE id_st='$id' AND urutan='54' LIMIT 1";
   mysqli_query($con, $qry) or die(mysqli_error($con));
   $qry="UPDATE personil_st SET nama='$nama55',jabatan_st='$jabatan55' WHERE id_st='$id' AND urutan='55' LIMIT 1";
   mysqli_query($con, $qry) or die(mysqli_error($con));
   $qry="UPDATE personil_st SET nama='$nama56',jabatan_st='$jabatan56' WHERE id_st='$id' AND urutan='56' LIMIT 1";
   mysqli_query($con, $qry) or die(mysqli_error($con));
   $qry="UPDATE personil_st SET nama='$nama57',jabatan_st='$jabatan57' WHERE id_st='$id' AND urutan='57' LIMIT 1";
   mysqli_query($con, $qry) or die(mysqli_error($con));
   $qry="UPDATE personil_st SET nama='$nama58',jabatan_st='$jabatan58' WHERE id_st='$id' AND urutan='58' LIMIT 1";
   mysqli_query($con, $qry) or die(mysqli_error($con));
   $qry="UPDATE personil_st SET nama='$nama59',jabatan_st='$jabatan59' WHERE id_st='$id' AND urutan='59' LIMIT 1";
   mysqli_query($con, $qry) or die(mysqli_error($con));
   $qry="UPDATE personil_st SET nama='$nama60',jabatan_st='$jabatan60' WHERE id_st='$id' AND urutan='60' LIMIT 1";
   mysqli_query($con, $qry) or die(mysqli_error($con));
   $qry="UPDATE personil_st SET nama='$nama61',jabatan_st='$jabatan61' WHERE id_st='$id' AND urutan='61' LIMIT 1";
   mysqli_query($con, $qry) or die(mysqli_error($con));
   $qry="UPDATE personil_st SET nama='$nama62',jabatan_st='$jabatan62' WHERE id_st='$id' AND urutan='62' LIMIT 1";
   mysqli_query($con, $qry) or die(mysqli_error($con));
   $qry="UPDATE personil_st SET nama='$nama63',jabatan_st='$jabatan63' WHERE id_st='$id' AND urutan='63' LIMIT 1";
   mysqli_query($con, $qry) or die(mysqli_error($con));
   $qry="UPDATE personil_st SET nama='$nama64',jabatan_st='$jabatan64' WHERE id_st='$id' AND urutan='64' LIMIT 1";
   mysqli_query($con, $qry) or die(mysqli_error($con));
   $qry="UPDATE personil_st SET nama='$nama65',jabatan_st='$jabatan65' WHERE id_st='$id' AND urutan='65' LIMIT 1";
   mysqli_query($con, $qry) or die(mysqli_error($con));
   
   header("location:dataStPertahunAdm.php?page_a=$page_a&tahun=$tahun&page=$page&message=notifEdit");
   ?>