<?php include ("contentsConAdm.php");
   
   $id=mysqli_real_escape_string($con, $_POST['id']);
   $page= mysqli_real_escape_string($con, $_POST['page']);
   $date= mysqli_real_escape_string($con, $_POST['date']);
   $no_agenda_surat=mysqli_real_escape_string($con, $_POST['no_agenda_surat']);
   $tujuan_prak=mysqli_real_escape_string($con, $_POST['tujuan_prak']);
   $sebutan_pimpinan=mysqli_real_escape_string($con, $_POST['sebutan_pimpinan']);
   $kota_prak=mysqli_real_escape_string($con, $_POST['kota_prak']);
   $jenjang_testee=mysqli_real_escape_string($con, $_POST['jenjang_testee']);
   $matkul=mysqli_real_escape_string($con, $_POST['matkul']);
   $waktu=mysqli_real_escape_string($con, $_POST['waktu']);
   $jam=mysqli_real_escape_string($con, $_POST['jam']);
   $tgl_dikeluarkan=mysqli_real_escape_string($con, $_POST['tgl_dikeluarkan']);
   $tgl_proses=date('d-m-Y');
   $tembusan=mysqli_real_escape_string($con, $_POST['tembusan']);
   $statusform=mysqli_real_escape_string($con, '2');
   $executor=mysqli_real_escape_string($con, $_POST['executor']);
   
   $testee1=mysqli_real_escape_string($con, $_POST['testee1']);
   $testee2=mysqli_real_escape_string($con, $_POST['testee2']);
   $testee3=mysqli_real_escape_string($con, $_POST['testee3']);
   $testee4=mysqli_real_escape_string($con, $_POST['testee4']);
   $testee5=mysqli_real_escape_string($con, $_POST['testee5']);
   $testee6=mysqli_real_escape_string($con, $_POST['testee6']);
   $testee7=mysqli_real_escape_string($con, $_POST['testee7']);
   $testee8=mysqli_real_escape_string($con, $_POST['testee8']);
   $testee9=mysqli_real_escape_string($con, $_POST['testee9']);
   $testee10=mysqli_real_escape_string($con, $_POST['testee10']);
   $testee11=mysqli_real_escape_string($con, $_POST['testee11']);
   $testee12=mysqli_real_escape_string($con, $_POST['testee12']);
   $testee13=mysqli_real_escape_string($con, $_POST['testee13']);
   $testee14=mysqli_real_escape_string($con, $_POST['testee14']);
   $testee15=mysqli_real_escape_string($con, $_POST['testee15']);
   $testee16=mysqli_real_escape_string($con, $_POST['testee16']);
   $testee17=mysqli_real_escape_string($con, $_POST['testee17']);
   $testee18=mysqli_real_escape_string($con, $_POST['testee18']);
   $testee19=mysqli_real_escape_string($con, $_POST['testee19']);
   $testee20=mysqli_real_escape_string($con, $_POST['testee20']);
   
   $myqry="UPDATE siprak_siswa SET no_agenda_surat='$no_agenda_surat',tujuan_prak='$tujuan_prak',sebutan_pimpinan='$sebutan_pimpinan',kota_prak='$kota_prak',jenjang_testee='$jenjang_testee',matkul='$matkul',waktu='$waktu',jam='$jam',tgl_proses='$tgl_proses',tgl_dikeluarkan='$tgl_dikeluarkan',tembusan='$tembusan',statusform='$statusform',executor='$executor' WHERE id='$id' LIMIT 1";
       mysqli_query($con, $myqry) or die(mysqli_error($con));
   $qry="UPDATE testee_siprak SET nama_testee='$testee1' WHERE id_siprak='$id' AND urutan='1' LIMIT 1";
       mysqli_query($con, $qry) or die(mysqli_error($con));
   $qry="UPDATE testee_siprak SET nama_testee='$testee2' WHERE id_siprak='$id' AND urutan='2' LIMIT 1";
       mysqli_query($con, $qry) or die(mysqli_error($con));
   $qry="UPDATE testee_siprak SET nama_testee='$testee3' WHERE id_siprak='$id' AND urutan='3' LIMIT 1";
       mysqli_query($con, $qry) or die(mysqli_error($con));
   $qry="UPDATE testee_siprak SET nama_testee='$testee4' WHERE id_siprak='$id' AND urutan='4' LIMIT 1";
       mysqli_query($con, $qry) or die(mysqli_error($con));
   $qry="UPDATE testee_siprak SET nama_testee='$testee5' WHERE id_siprak='$id' AND urutan='5' LIMIT 1";
       mysqli_query($con, $qry) or die(mysqli_error($con));
   $qry="UPDATE testee_siprak SET nama_testee='$testee6' WHERE id_siprak='$id' AND urutan='6' LIMIT 1";
       mysqli_query($con, $qry) or die(mysqli_error($con));
   $qry="UPDATE testee_siprak SET nama_testee='$testee7' WHERE id_siprak='$id' AND urutan='7' LIMIT 1";
       mysqli_query($con, $qry) or die(mysqli_error($con));
   $qry="UPDATE testee_siprak SET nama_testee='$testee8' WHERE id_siprak='$id' AND urutan='8' LIMIT 1";
       mysqli_query($con, $qry) or die(mysqli_error($con));
   $qry="UPDATE testee_siprak SET nama_testee='$testee9' WHERE id_siprak='$id' AND urutan='9' LIMIT 1";
       mysqli_query($con, $qry) or die(mysqli_error($con));
   $qry="UPDATE testee_siprak SET nama_testee='$testee10' WHERE id_siprak='$id' AND urutan='10' LIMIT 1";
       mysqli_query($con, $qry) or die(mysqli_error($con));
   $qry="UPDATE testee_siprak SET nama_testee='$testee11' WHERE id_siprak='$id' AND urutan='11' LIMIT 1";
       mysqli_query($con, $qry) or die(mysqli_error($con));
   $qry="UPDATE testee_siprak SET nama_testee='$testee12' WHERE id_siprak='$id' AND urutan='12' LIMIT 1";
       mysqli_query($con, $qry) or die(mysqli_error($con));
   $qry="UPDATE testee_siprak SET nama_testee='$testee13' WHERE id_siprak='$id' AND urutan='13' LIMIT 1";
       mysqli_query($con, $qry) or die(mysqli_error($con));
   $qry="UPDATE testee_siprak SET nama_testee='$testee14' WHERE id_siprak='$id' AND urutan='14' LIMIT 1";
       mysqli_query($con, $qry) or die(mysqli_error($con));
   $qry="UPDATE testee_siprak SET nama_testee='$testee15' WHERE id_siprak='$id' AND urutan='15' LIMIT 1";
       mysqli_query($con, $qry) or die(mysqli_error($con));
   $qry="UPDATE testee_siprak SET nama_testee='$testee16' WHERE id_siprak='$id' AND urutan='16' LIMIT 1";
       mysqli_query($con, $qry) or die(mysqli_error($con));
   $qry="UPDATE testee_siprak SET nama_testee='$testee17' WHERE id_siprak='$id' AND urutan='17' LIMIT 1";
       mysqli_query($con, $qry) or die(mysqli_error($con));
   $qry="UPDATE testee_siprak SET nama_testee='$testee18' WHERE id_siprak='$id' AND urutan='18' LIMIT 1";
       mysqli_query($con, $qry) or die(mysqli_error($con));
   $qry="UPDATE testee_siprak SET nama_testee='$testee19' WHERE id_siprak='$id' AND urutan='19' LIMIT 1";
       mysqli_query($con, $qry) or die(mysqli_error($con));
   $qry="UPDATE testee_siprak SET nama_testee='$testee20' WHERE id_siprak='$id' AND urutan='20' LIMIT 1";
       mysqli_query($con, $qry) or die(mysqli_error($con));
   
    header("location:rekapSiprakSiswaKelAdm.php?date=$date&page=$page&message=notifEdit");
   ?>